### ISSUE TITLE
The table under "Files upload" in add and edit mode should not show the horizontal scrollbar

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#10]
1. The table under "Files upload" in "add" and "edit" mode should not show the horizontal scrollbar.
2. When there is no data in the table should show "No files uploaded"
![hidden](https://cloud.githubusercontent.com/assets/11714762/19233579/00446670-8f04-11e6-97ff-d4614dff005f.png)

**Comment by nevesseq** [comment]
fixed
