### ISSUE TITLE
The UI for purchase basket for different sellers are different

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#100]
Seller : company (the purchase basket UI looks as follows)
![image](https://cloud.githubusercontent.com/assets/11714762/19596680/5e9019ca-97ad-11e6-892b-c8533cc16b8c.png)

seller: 102health (the purchase basket UI looks as follows)
![image](https://cloud.githubusercontent.com/assets/11714762/19596707/7acdb8c2-97ad-11e6-8837-59a7f906f153.png)

Needs to be same

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Thanx. Tested
