### ISSUE TITLE
Seller SKU, destination ware house and seller name allowed to be repeated in purchase basket

### ISSUE THREAD

**Issue by ashika123** [ajency/PO#103]
Add SKU to the purchase basket
Change the destination warehouse 
Click on save.

Current behaviour: Same SKU gets added to the basket
Expected behaviour: Shouldn't allow to add the same SKU to the purchase basket.
![same sku](https://cloud.githubusercontent.com/assets/9797052/19645060/81718e50-9a10-11e6-9b40-cb18b770f475.jpg)

**Comment by Divyagawas** [comment]
Still can add

![image](https://cloud.githubusercontent.com/assets/11714762/19923884/81f6fe7c-a10f-11e6-83a9-25f3c557db7f.png)
