### ISSUE TITLE
Seller status does not change when stocked out

### ISSUE THREAD

**Issue by ashika123** [ajency/PO#1037]
For listing Id: B01M0FPFXZ
Out of 36 sellers 33 stocked out
Current behavior: The status of all the sellers is shown as active
Expected: The seller status had to be stocked out

**Comment by cyrus2021** [comment]
@robuil. api:- http://repricer-api.ajency.in/api/products/all?limit=20&page=1&sort=created_at&direction=desc

under "sellers" array in the response please check "is_stocked_out" flag

**Comment by ashika123** [comment]
Tested. For stocked out status seller shown as disabled
