### ISSUE TITLE
Incorrect behaviour on browser back from purchase basket

### ISSUE THREAD

**Issue by ashika123** [ajency/PO#104]
Select product from product list
Add to purchase basket
Click on back

Current behaviour: SKU is shown as selected and the button is not highlighted
Expected: Back should not show the SKU selected 
![incorrect](https://cloud.githubusercontent.com/assets/9797052/19645829/68d2e304-9a14-11e6-9e22-e7ebc6397add.jpg)

**Comment by trilokajency** [comment]
Browser back button doesnot refresh the page

**Comment by Divyagawas** [comment]
Tested
