### ISSUE TITLE
Highlight colour for the message has to be changed 

### ISSUE THREAD

**Issue by ashika123** [ajency/PO#105]
Refer:
https://docs.google.com/presentation/d/1JAbDWP327Gs-1OVHkAdBY_OL0HL416SBOqV68hQH3YA/edit#slide=id.g118a9c15b8_0_19

![high](https://cloud.githubusercontent.com/assets/9797052/19646660/13950878-9a18-11e6-92f8-cc5fd37e0ccf.jpg)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested
