### ISSUE TITLE
In supplier view mode if there are no warehouse added then should give a option to add warehouse

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#11]
In supplier view mode if there are no warehouse added then should give a option to add warehouse, as in billing details in http://www.btapp.ajency.in/suppliers/view/25

![image](https://cloud.githubusercontent.com/assets/11714762/19233804/74dea062-8f05-11e6-84ba-8c51b7cc32e0.png)

**Comment by trilokajency** [comment]
Fixed
