### ISSUE TITLE
staging|Prices -  Violation filter not functioning|displaying products even if violation is false

### ISSUE THREAD

**Issue by harshitaajency** [ajency/PO#1149]
staging|Prices -  Violation filter not functioning|displaying products even if violation is false for that product

http://repricer.staging.browntape.com/prices/all?limit=20&page=1&includesellers=no&sort=created_at&direction=desc&filters%5Bpricing_outcome%5D=is_violation

**Comment by robiulpro** [comment]
Fixed, should be working on next crawl.
