### ISSUE TITLE
Staging|Prices tab - all the listings marked as pink

### ISSUE THREAD

**Issue by harshitaajency** [ajency/PO#1158]
Staging|Prices tab - all the listings marked as pink
There is no violations for some of the listings , still marked as pink

![image](https://user-images.githubusercontent.com/19776994/29562455-082b3bc4-8757-11e7-9bf7-407c9d02d484.png)

![image](https://user-images.githubusercontent.com/19776994/29562536-4415dcde-8757-11e7-896c-5acacf26c11e.png)

**Comment by robiulpro** [comment]
Fixed, should be working on next crawl.

**Comment by harshitaajency** [comment]
Some of the listings still marked as pink (violated). Even when there is no violations

**Comment by robiulpro** [comment]
Fixed.
