### ISSUE TITLE
Staging|Sellers popup - bb ownership value not displayed

### ISSUE THREAD

**Issue by harshitaajency** [ajency/PO#1159]
Staging|Sellers popup - bb ownership value not displayed

![image](https://user-images.githubusercontent.com/19776994/29562765-48dd1146-8758-11e7-92b0-31e15f5f3c73.png)

**Comment by robiulpro** [comment]
We dont have the bb ownership data now, removed bb ownership generate function from crawler as the data was wrong. In next release we can generate the accurate data.

**Comment by robiulpro** [comment]
Same for stockouts.
