### ISSUE TITLE
staging|Seller popup Activity tab - Activity not displayed

### ISSUE THREAD

**Issue by harshitaajency** [ajency/PO#1170]
staging|Seller popup Activity tab - Activity not displayed

Screenshot of staging: 
![image](https://user-images.githubusercontent.com/19776994/29604028-cf1f7ce8-8803-11e7-87b3-3479c671b2df.png)

Screenshot of live: 
![image](https://user-images.githubusercontent.com/19776994/29604071-f01ae2de-8803-11e7-95e0-c84a7802a61a.png)

**Comment by robiulpro** [comment]
We have removed rating count change activities
