### ISSUE TITLE
staging|review star value displayed with rounded figure i.e 4.5 star displayed as 5 star

### ISSUE THREAD

**Issue by harshitaajency** [ajency/PO#1171]
staging|review star value displayed with rounded figure i.e 4.5 star displayed as 5 star

Screenshot : 
![image](https://user-images.githubusercontent.com/19776994/29604253-8a7337c8-8804-11e7-8e58-7d90fa9fd239.png)

![image](https://user-images.githubusercontent.com/19776994/29604214-71b1c5e2-8804-11e7-8d7f-f4ef557765e1.png)

**Comment by robiulpro** [comment]
Fixed. wait for the next carawl
