### ISSUE TITLE
Staging-same sheet can be imported for the same seller id

### ISSUE THREAD

**Issue by ashika123** [ajency/PO#1173]
http://repricer.staging.browntape.com/import
on staging imported a same sheet as previously uploaded with same seller id

Current behavior: Allowed to upload the sheet
![upload](https://user-images.githubusercontent.com/9797052/29615321-1a50969e-882b-11e7-959c-52290fd2953a.png)

**Comment by antoniojfurtado** [comment]
This is intended behavior, however credits will not be deducted as you can see in the message 22 products are imported but 0 credits used as they are not new products
