### ISSUE TITLE
staging|On applying market place filter, clears all the other filters

### ISSUE THREAD

**Issue by harshitaajency** [ajency/PO#1191]
staging|On applying market place filter, clears all the other filters

Steps to replicate: 
1. Open Prices tab (All)
2. Apply any filter (eg: I have buybox) -> filtered results will be displayed
3. click on flipkart tab
Current Benaviour: Clears "I have buybox filter"
Expected: should not clear previous filter

**Comment by anujkhurana** [comment]
we can close this bug.
