### ISSUE TITLE
Status on import details popup is incorrect. displayed as "pending" when status of the sheet is "crawling"

### ISSUE THREAD

**Issue by harshitaajency** [ajency/PO#1194]
Status on import details popup is incorrect. displayed as "pending" when status of the sheet is "crawling"

![image](https://user-images.githubusercontent.com/19776994/29817497-d75665b2-8cd5-11e7-9602-6b50a33df947.png)

![image](https://user-images.githubusercontent.com/19776994/29817545-090a0370-8cd6-11e7-98f1-1bc2cd8b65cd.png)

**Comment by antoniojfurtado** [comment]
When Importing products the crawl status of all products is set to Impoting, only when scheduler runs and pics products to be crawled the status is marked as crawling.
