### ISSUE TITLE
staging|last updated time is not displayed

### ISSUE THREAD

**Issue by harshitaajency** [ajency/PO#1196]
staging|last updated time is not displayed

Screenshot: 
![image](https://user-images.githubusercontent.com/19776994/29818472-1a361108-8cda-11e7-89d6-d0bd414d51d2.png)

**Comment by harshitaajency** [comment]
credentials : dal13+s@mailinator.com  ; ajency#123

**Comment by cyrus2021** [comment]
api needs to send in the time

**Comment by harshitaajency** [comment]
Fixed
