### ISSUE TITLE
staging|products not getting displayed on dashboard and price tab -  after import

### ISSUE THREAD

**Issue by harshitaajency** [ajency/PO#1197]
staging|products not getting displayed on dashboard and price tab -  after import

As can be seen, file was imported at 5.30. It has been 18 min, still products not displayed

Screenshot: 
![image](https://user-images.githubusercontent.com/19776994/29820482-35e583e0-8ce2-11e7-8560-c967bba6224e.png)

![image](https://user-images.githubusercontent.com/19776994/29820448-1e84d458-8ce2-11e7-8f5d-89c903e29fc5.png)

**Comment by harshitaajency** [comment]
@antoniojfurtado also not displaying dummy products. when new user is created.

**Comment by antoniojfurtado** [comment]
Update summary process was terminated and never restarted by our script. Currently handled this with sh, will need to put try catch blocks in the php at appropriate places
