### ISSUE TITLE
Add products to PO from PO in draft status - The unit price should get prepopulated

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#129]
![8e8319ee-9d2e-11e6-94b8-1cbebff000ce](https://cloud.githubusercontent.com/assets/11714762/19805224/c42a1b22-9d30-11e6-962f-85d9100e08f8.png)

**Comment by Divyagawas** [comment]
Still the price is not getting populated. please check

**Comment by trilokajency** [comment]
Please clear you cache, as its working fine for me

**Comment by Divyagawas** [comment]
Works
