### ISSUE TITLE
supplier view | "+" icon on contact information section can be replaced with an "add more" button

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#13]
"+" icon on contact information section can be replaced with an "add more" button to be more clear
![hidden](https://cloud.githubusercontent.com/assets/11714762/19234058/e2f76786-8f06-11e6-86d8-c2afeb8fd265.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested
