### ISSUE TITLE
Same SKU can be added to the PO multiple times

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#134]
http://www.btapp.ajency.in/purchase_orders/view/20

![2](https://cloud.githubusercontent.com/assets/11714762/19806560/66c84afe-9d39-11e6-92fd-01b9f0d37af3.png)

**Comment by Divyagawas** [comment]
Tested, works. But shows the same message "sku already exists" even when a different sku is added

**Comment by Divyagawas** [comment]
"Already exists" message doesn't come for the SKU's which already exists in PO

**Comment by trilokajency** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested
