### ISSUE TITLE
For contact information, warehouse and billing details please remove "delete" button if there is only one contact, warehouse or billing address added

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#16]
For View mode of "contact information", "warehouse" and "billing details" please remove "delete" button if there is only one contact, warehouse or billing address added instead of showing the message "at least one billing information is required"

![hidden](https://cloud.githubusercontent.com/assets/11714762/19234348/ac0e1e0c-8f08-11e6-821e-55bea35358ac.png)

**Comment by trilokajency** [comment]
Delete icon was displayed as if there are multiple contact information and the user wants to delete the 1st one and want to keep the remaining contacts.
Validation has been made so at least 1 contact information has to exist.

**Comment by Divyagawas** [comment]
OK thanx
