### ISSUE TITLE
'Add new' on any tab should show the section title

### ISSUE THREAD

**Issue by ashika123** [ajency/PO#17]
Section title is not shown when clicked on Add new 
![section title](https://cloud.githubusercontent.com/assets/9797052/19236053/dc8c1516-8f12-11e6-8bdb-db6ea10fc882.jp

**Comment by nevesseq** [comment]
fixed

**Comment by ashika123** [comment]
Not fixed for warehouse and billing details

**Comment by Divyagawas** [comment]
tested
