### ISSUE TITLE
All filters needs to be moved on top

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#194]
The filters which are currently added in the table needs to be separated out and added on the top of the table on all pages
Please refer: https://projects.invisionapp.com/share/FP83MFVJQ/#/screens/175945868_02_Orders_V5_9_2_1_New

**Comment by nevesseq** [comment]
done, functionality is to be handled by @trilokajency

**Comment by Divyagawas** [comment]
@trilokajency please check this, the UI has already been done by neves.
