### ISSUE TITLE
Change title of the pop up "add sku's to puchase basket" to "Add to purchase basket"

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#197]
Change title of the pop up "add sku's to puchase basket" to "Add to purchase basket"
![5](https://cloud.githubusercontent.com/assets/11714762/19929643/4c0a954c-a12a-11e6-9586-183c46f29ea2.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested.Thanx
