### ISSUE TITLE
single PO | Total number of quantity has to be aligned properly

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#198]
![6](https://cloud.githubusercontent.com/assets/11714762/19956276/840c330c-a1b0-11e6-8676-f46e2954d80e.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
- The total is repeated twice, Please check
- The font color is too light please refer : https://docs.google.com/presentation/d/1JAbDWP327Gs-1OVHkAdBY_OL0HL416SBOqV68hQH3YA/edit?ts=57eb6fa3#slide=id.p14
