### ISSUE TITLE
Total at the bottom of the PO single page needs to be changed

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#199]
Please refer : https://docs.google.com/presentation/d/1JAbDWP327Gs-1OVHkAdBY_OL0HL416SBOqV68hQH3YA/edit?ts=57eb6fa3#slide=id.p15

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
The input boxes and other text on the line be smaller.
