### ISSUE TITLE
The left hand menu breaks on branches page

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#200]
The left hand menu breaks on branches page http://www.btapp.ajency.in/shipping_batches/#/batches/

![6](https://cloud.githubusercontent.com/assets/11714762/19956263/4cf95f20-a1b0-11e6-8400-edb57ed8832e.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested
