### ISSUE TITLE
Incorrect PO grand total when the qty of the item or price is edited

### ISSUE THREAD

**Issue by ashika123** [ajency/PO#217]
Go to a single PO
Edit the total qty
Click on update 
Refresh the page

Current behavior: The qty of the item becomes 0 on refresh

**Comment by Divyagawas** [comment]
If there are more than 1 SKU in the basket and if tried to edit the price, shows html tags in the input box
![7](https://cloud.githubusercontent.com/assets/11714762/20047294/bb92e052-a4d8-11e6-805d-e0d2ad3c90cd.png)

**Comment by Divyagawas** [comment]
Tested
