### ISSUE TITLE
Total price and grand total on PO has to be in decimal

### ISSUE THREAD

**Issue by ashika123** [ajency/PO#218]
![decimal](https://cloud.githubusercontent.com/assets/9797052/19995177/ed841b36-a27a-11e6-938a-1ab2f72fc470.jpg)

**Comment by Divyagawas** [comment]
When a new product is added the total of that product is shown 0. 

![7](https://cloud.githubusercontent.com/assets/11714762/20047246/51fb31da-a4d8-11e6-855b-65056a055d9d.png)

**Comment by Divyagawas** [comment]
Tested
