### ISSUE TITLE
Incorrect warehouse is displayed when the PO is scanned 

### ISSUE THREAD

**Issue by ashika123** [ajency/PO#226]
On scanning the PO incorrect warehouse  is displayed
Expected: The destination warehouse(ship to) on the PO has to be displayed 
![grn warehouse](https://cloud.githubusercontent.com/assets/9797052/20002510/40c6b61a-a2a7-11e6-924a-928fc2007d3d.jpg)

**Comment by Divyagawas** [comment]
Warehouse is not shown on the view GRN mode
![8](https://cloud.githubusercontent.com/assets/11714762/20088449/227412fa-a5a6-11e6-8570-aaa8e28d1cb7.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested
