### ISSUE TITLE
GRN | Need to put (*)  for the mandatory feilds

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#250]
![7](https://cloud.githubusercontent.com/assets/11714762/20053356/244c3d9e-a4fe-11e6-9c33-acce0592829d.png)

**Comment by Divyagawas** [comment]
The label is missaligned
![8](https://cloud.githubusercontent.com/assets/11714762/20087188/3f47518a-a59c-11e6-97a9-06fb09f152ac.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested
