### ISSUE TITLE
GRN | 'Phone number field' always shows a default value

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#283]
Test:
1. Navigate to GRN listing page
2. Click on 'New GRN'
3. Scan a PO
4. Fill in all the details and click on the 'create' button - this will open the edit page
5. Edit the necessary details and click on 'save' - opens the view page

Current : The phone number is not the same as what was entered while creating the GRN (Shows some default value)

Expected: Should show the same phone number which was entered in the 'phone number' feild while GRN creation

Example:
![8](https://cloud.githubusercontent.com/assets/11714762/20098179/7acac354-a5d8-11e6-83e3-0f49e30d0072.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested
