### ISSUE TITLE
GRN view | count next to GRN tab is incorrect

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#284]
Test:
Navigate to any GRN i.e the single GRN view page

Current : The count next to the GRN tab shown is incorrect

Expected: Should show the count of all the GRN's created till date

![8](https://cloud.githubusercontent.com/assets/11714762/20098529/570a9604-a5da-11e6-9073-fb972167e2e8.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested
