### ISSUE TITLE
GRN | When on QC pending, the count next to each status tab is incorrect

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#285]
Test:
Navigate to GRN.
Click on the 'QC pending' tab

Current : the count shown next to each status tab is incorrect
Ex: 'ALL' - 13 and 'cancelled' -0
![8](https://cloud.githubusercontent.com/assets/11714762/20099781/5faf7850-a5e0-11e6-9a09-f8b05d3ff210.png)

Expected: There are total 17 so 'ALL' tab should show a count of 17 and cancelled should show a count of 4
![8](https://cloud.githubusercontent.com/assets/11714762/20099764/4b7edc68-a5e0-11e6-943f-f14666dbe543.png)

**Comment by Divyagawas** [comment]
same when on tab 'cancelled'
![image](https://cloud.githubusercontent.com/assets/11714762/20099811/7f0fca38-a5e0-11e6-8d67-41a570454f41.png)

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Tested
