### ISSUE TITLE
The PO code generated should be client level 

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#288]
Choose One client.
Create PO
Go to other clients profile create a new PO
The series is followed over here

Expected: Should be client level - EX: Should not follow the series but start with 00001

**Comment by robiulpro** [comment]
Fixed

**Comment by Divyagawas** [comment]
Is client level but only 1 digit - Please make it 5 digits

**Comment by robiulpro** [comment]
FIxed

**Comment by Divyagawas** [comment]
Tested
