### ISSUE TITLE
When navigating to 'product list' shows a 'add to Purchase basket' pop up

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#298]
When navigating to 'product list' shows a 'add to Purchase basket' pop up and disappears after some time
![9](https://cloud.githubusercontent.com/assets/11714762/20136889/5af6dcd2-a69d-11e6-851b-b02d0b54e01d.png)

**Comment by Divyagawas** [comment]
Not fixed. Still facing the issue

**Comment by nevesseq** [comment]
fixed
