### ISSUE TITLE
GRN tab inside PO

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#319]
A GRN tab needs to be created for a PO to show list all the GRNs in which the particular PO in included

Please refer: https://docs.google.com/presentation/d/1JAbDWP327Gs-1OVHkAdBY_OL0HL416SBOqV68hQH3YA/edit?ts=57eb6fa3#slide=id.g10abab5eeb_5_37

**Comment by robiulpro** [comment]
Completed

**Comment by Divyagawas** [comment]
tested
