### ISSUE TITLE
Single PO view page | 'Add GRN' button for Single PO

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#320]
When the PO status is Ordered - There should appear a button 'Add GRN' which on click creates a new GRN for the particular PO

https://docs.google.com/presentation/d/1JAbDWP327Gs-1OVHkAdBY_OL0HL416SBOqV68hQH3YA/edit?ts=57eb6fa3#slide=id.p17

**Comment by robiulpro** [comment]
Completed

**Comment by Divyagawas** [comment]
After GRN is created, the 'item received table keeps on loading
![image](https://cloud.githubusercontent.com/assets/11714762/20299597/a36f5a0e-ab41-11e6-9bc5-043d269be24e.png)

**Comment by Divyagawas** [comment]
Fixed.
