### ISSUE TITLE
PO single page | PO status(colored) besides the PO code

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#336]

**Comment by nevesseq** [comment]
done

**Comment by Divyagawas** [comment]
Can we have the following colors for the statuses : All the positive status to be green and negative to be red as mentioned below
1. Draft - light grey
2. Under review - Dark grey
3. Approved - Light green
4. Ordered - Yellow (Same as used on status bar)
5. Received - Light green
6. Partially received - Light green
7. Completed - Light green
8. Closed - Black
9. Cancelled - Red
10. Rejected - Red

**Comment by nevesseq** [comment]
done
