### ISSUE TITLE
Rearranging the PO status tabs 

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#341]
The order that should be followed for displaying status tabs is as follows (After closed add a pipe like seperator)
Draft
Under Review
Approved
Ordered
Partially Received
Completed
Closed
Cancelled
Rejected
All

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Cancelled has to be moved after the pipe like seperator

**Comment by nevesseq** [comment]
fixed
