### ISSUE TITLE
The drop down for clients profile on top does'not work

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#346]
![11](https://cloud.githubusercontent.com/assets/11714762/20215975/e3a11722-a83d-11e6-950d-1e61f5ec5cea.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
![image](https://cloud.githubusercontent.com/assets/11714762/20341264/72205384-ac0b-11e6-8567-9163e4ebb0c6.png)

**Comment by Divyagawas** [comment]
Thanx
