### ISSUE TITLE
View mode for warehouse and billing details is breaking

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#37]
![image](https://cloud.githubusercontent.com/assets/11714762/19350094/0374659e-9174-11e6-8010-f17ee0dcbe09.png)

![image](https://cloud.githubusercontent.com/assets/11714762/19350099/08b3fe98-9174-11e6-9172-4479d1e88652.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
tested
