### ISSUE TITLE
When the GRN is closed all the activities dissapear

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#381]
![image](https://cloud.githubusercontent.com/assets/11714762/20379487/813d1070-acc2-11e6-8a96-4104510fe374.png)

**Comment by robiulpro** [comment]
you have been signed out, please sign in again

**Comment by Divyagawas** [comment]
Ok thanx. But after update the grn status is changed to 'Closed' which is not shown in the activity
![image](https://cloud.githubusercontent.com/assets/11714762/20379608/27de20ae-acc3-11e6-83ec-e68a4f255844.png)
