### ISSUE TITLE
Disable 'select all' check box from top of the items filter in GRN

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#395]
Disable 'select all' check box from top of the items filter in GRN as there are no check boxes for the list of items and no action buttons
![111](https://cloud.githubusercontent.com/assets/11714762/20513302/09b7a74e-b0ab-11e6-864c-ed2fcf72cd1a.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested
