### ISSUE TITLE
Message on deleteing the last item from the PO needs formatting

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#402]
Current Message:  This is the last product can not delete it, PO should contain at least one product
Expected Message: Cannot delete this product, PO should contain at least one product.

![image](https://cloud.githubusercontent.com/assets/11714762/20556256/4a12df2a-b18c-11e6-86a6-329432c74501.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested
