### ISSUE TITLE
blank activity page - UI breaks

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#412]
![44](https://cloud.githubusercontent.com/assets/11714762/20616584/3589c32e-b309-11e6-9ff3-43aaa42c0e73.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
don't show the 'previous' and 'next' button when they are disabled
![image](https://cloud.githubusercontent.com/assets/11714762/20788106/50ce8b58-b7d5-11e6-818f-f4393402ecc9.png)
