### ISSUE TITLE
PO |The number (item count) on top of each tab needs to be removed and added at the side to the tab label

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#432]
The number (item count) on top of each tab(highlighted in the screenshot) needs to be removed and added at the side to the tab label ex: Items (1)

![12](https://cloud.githubusercontent.com/assets/11714762/20709773/3fed077a-b65d-11e6-8282-f5729debadac.png)

**Comment by nevesseq** [comment]
done
