### ISSUE TITLE
GRN |The number (item count) on top of each tab needs to be removed and added at the side to the tab label

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#433]
The number (item count) on top of each tab(highlighted in the screenshot) needs to be removed and added at the side to the tab label ex: Items Received (4)
![12](https://cloud.githubusercontent.com/assets/11714762/20709901/d281c2e2-b65d-11e6-9671-5ab174f17268.png)

**Comment by nevesseq** [comment]
done
