### ISSUE TITLE
Remove comments from all the screens

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#446]
Hide comments icon and label from all the screens

po edit page
![image](https://cloud.githubusercontent.com/assets/11714762/20743046/062e06fe-b6fa-11e6-800e-dadddd1ad6e6.png)

Single po -details
![image](https://cloud.githubusercontent.com/assets/11714762/20743015/d7610984-b6f9-11e6-9e38-54bd38b09af0.png)

Single PO -Add to grn pop up
![image](https://cloud.githubusercontent.com/assets/11714762/20743027/e84632ec-b6f9-11e6-9c7e-52a9243140ce.png)

Creating new grn page
![image](https://cloud.githubusercontent.com/assets/11714762/20743072/1f4eba02-b6fa-11e6-8075-ff48acc4fb44.png)

GRN details page - single GRN
![image](https://cloud.githubusercontent.com/assets/11714762/20743087/37f9fe68-b6fa-11e6-88f3-43698a68cbbd.png)

**Comment by nevesseq** [comment]
done
