### ISSUE TITLE
For PO and GRN code there should be a '#' prefix always

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#454]
On all the screens wherever po and grn codes are shown

GRN number on GRN tab for PO(ordered)
![image](https://cloud.githubusercontent.com/assets/11714762/20743894/b9ea4b40-b6fe-11e6-9253-c119ddce2467.png)

GRN listing page - for PO code and code displayed
![image](https://cloud.githubusercontent.com/assets/11714762/20743901/c8a4110c-b6fe-11e6-97b7-34276f76c952.png)

items table- under related PO's
![image](https://cloud.githubusercontent.com/assets/11714762/20743924/fca28f92-b6fe-11e6-85a7-5409591f0ef2.png)

**Comment by nevesseq** [comment]
done
