### ISSUE TITLE
Add items to PO | Add items pop up - UI has to be same as 'Add items' to catalog pop up

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#468]
the auto suggest has been adden to the pop up so the UI breaks - has to be styled as the pop up for 'add iems' in catalog(suppliers)
![image](https://cloud.githubusercontent.com/assets/11714762/20915150/0d06ec2a-bbaa-11e6-888d-d20bb5453964.png)

**Comment by nevesseq** [comment]
done
