### ISSUE TITLE
Single PO - create GRN pop up on the listing page needs to be styled

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#470]
Navigate to the PO listing page
for a PO status 'ordered' a button - +grn will be shown
click on the button - create GRN pop up opens
This pop up needs to be styled as the 'add GRN' pop up on single page
![image](https://cloud.githubusercontent.com/assets/11714762/20916466/fc836920-bbb1-11e6-9000-8c35b4cf9d9d.png)

Needs to be styled as
![image](https://cloud.githubusercontent.com/assets/11714762/20916489/0d64dfda-bbb2-11e6-8d34-296f3dc9f8e5.png)

**Comment by nevesseq** [comment]
done
