### ISSUE TITLE
PO pdf needs additional content

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#500]
Order of the columns in PO pdf: SKU code, Supplier SKU code, Description, Qty, Unit price and Total.
![12](https://cloud.githubusercontent.com/assets/11714762/21136219/c0898492-c14a-11e6-9901-40157d4d7210.png)

**Comment by Divyagawas** [comment]
At the bottom "Powered by Browntape"

**Comment by nevesseq** [comment]
done
