### ISSUE TITLE
Add supplier has |file upload button - move to left

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#513]
Edit suppliers
![image](https://cloud.githubusercontent.com/assets/11714762/21181454/0603913c-c224-11e6-8475-44b0f23d5ba9.png)

Add suppliers
![image](https://cloud.githubusercontent.com/assets/11714762/21181460/0da89c84-c224-11e6-8fa8-2e31624341ec.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
tested
