### ISSUE TITLE
Suppliers | Add catalog view and edit catalog view should be same

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#514]
Please change the add catalog view to be same as edit catalog view

Add catalog
![image](https://cloud.githubusercontent.com/assets/11714762/21181529/650cb0d2-c224-11e6-9e5e-7946205e54bd.png)

Edit catalog'
![image](https://cloud.githubusercontent.com/assets/11714762/21181535/6f133222-c224-11e6-8e4c-af79b8646c85.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
tested
