### ISSUE TITLE
Add GRN form - Remove numeric validation for 'Vendor invoice feild'

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#520]
Add grn po up on PO listing and PO(Ordered) single page - remove the numeric validation for 'Vendor Invoice' feild
![image](https://cloud.githubusercontent.com/assets/11714762/21212408/69f5279e-c2b2-11e6-8303-5eb53f6fcf6d.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
The vendor invoice feild is no more a numeric feild, if added some other value rather than number it does not show in the details tab for GRN
![17](https://cloud.githubusercontent.com/assets/11714762/21284724/ac94b8d2-c44a-11e6-994d-f485b8e8220f.png)
