### ISSUE TITLE
PO filters | change the list of statuses in the dropdown for 'status' filter 

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#534]
- Remove prefix 'submitted' from statuses - 'Under review, Approved, Rejected'
- Remove the statuses - Partially received, received and partially complete
- Move the status 'ordered' below 'approved'
![image](https://cloud.githubusercontent.com/assets/11714762/21284607/7f89014e-c446-11e6-89c8-8da7064b0d01.png)

**Comment by nevesseq** [comment]
statuses have to removed from DB, @trilokajency
