### ISSUE TITLE
The 'select all' for filters - make it to highlight like invision

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#536]
https://projects.invisionapp.com/share/FP83MFVJQ/#/screens/175945868_02_Orders_V5_9_2_1_New

![image](https://cloud.githubusercontent.com/assets/11714762/21284826/6e1797de-c44d-11e6-8ef8-4fe658478fad.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
- Make the checkboxed when inactive to be similar on all pages - Different on suppliers
- Highlights on Inactive checkboxes can be removed

**Comment by nevesseq** [comment]
done
