### ISSUE TITLE
Pdf seller SKU code breaks

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#559]
![image](https://cloud.githubusercontent.com/assets/11714762/21390393/c74ae236-c7ac-11e6-9a77-97ca8ee195f1.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Still the seller sku code is moving out of the column, please check
![image](https://cloud.githubusercontent.com/assets/11714762/21449228/0cd94436-c911-11e6-83cd-e9c42abaffae.png)
