### ISSUE TITLE
Date format readable on PO single page, GRN single page

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#584]
PO single page
![image](https://cloud.githubusercontent.com/assets/11714762/21492779/804e025c-cc2d-11e6-8ae5-48d423d148c2.png)

GRN single page
![image](https://cloud.githubusercontent.com/assets/11714762/21492950/a39d2fca-cc2e-11e6-960a-3e0239e2204b.png)

**Comment by Divyagawas** [comment]
Shows different created date in the single page and diffent on listing page

**Comment by trilokajency** [comment]
Both dates are different
1 is created date that is shown on listing page and the date which is shown on the view page is Vendor Invoice Date
