### ISSUE TITLE
Billing details- label on the edit pop up is missing

### ISSUE THREAD

**Issue by ashika123** [ajency/PO#59]

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
The label is still miss aligned
![18](https://cloud.githubusercontent.com/assets/11714762/19475703/0f2bf432-9553-11e6-9876-9cd58cd0aebe.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested
