### ISSUE TITLE
Edit icon has to be consistent on all pages 

### ISSUE THREAD

**Issue by ashika123** [ajency/PO#594]
![edit 1](https://cloud.githubusercontent.com/assets/9797052/21515203/840f2ef4-ccf3-11e6-8c0e-b7ee8fcea8fc.jpg)
![edit 2](https://cloud.githubusercontent.com/assets/9797052/21515205/886ee62e-ccf3-11e6-9491-f4acfe1b6be4.jpg)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Reduce the padding
![parent](https://cloud.githubusercontent.com/assets/11714762/21565120/fa3cdf96-ceb9-11e6-8e30-5731552b9fd5.png)
