### ISSUE TITLE
Supplier priority page |View - Please increase the column size and add scroll bar

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#615]
Please increase the column size and add scroll bar as in https://docs.google.com/presentation/d/1JAbDWP327Gs-1OVHkAdBY_OL0HL416SBOqV68hQH3YA/edit?ts=57eb6fa3#slide=id.g1193d23a40_20_90

![currently](https://cloud.githubusercontent.com/assets/11714762/21678521/2a27c540-d365-11e6-996d-1154466376dd.png)

**Comment by nevesseq** [comment]
fixed
