### ISSUE TITLE
Supplier priority page |Edit - Please increase the column size and add scroll bar

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#616]
Please increase the column size and add scroll bar as in https://docs.google.com/presentation/d/1JAbDWP327Gs-1OVHkAdBY_OL0HL416SBOqV68hQH3YA/edit?ts=57eb6fa3#slide=id.g1193d23a40_20_90
![image](https://cloud.githubusercontent.com/assets/11714762/21678622/b0b0cefe-d365-11e6-9d5c-16b225c4c0f2.png)
https://docs.google.com/presentation/d/1JAbDWP327Gs-1OVHkAdBY_OL0HL416SBOqV68hQH3YA/edit?ts=57eb6fa3#slide=id.g1193d23a40_20_90

**Comment by nevesseq** [comment]
fixed
