### ISSUE TITLE
Search icon make non clickable

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#651]
![image](https://cloud.githubusercontent.com/assets/11714762/21882901/81e306e2-d8d2-11e6-96f8-0bef19c1ae6a.png)

**Comment by nevesseq** [comment]
done

**Comment by Divyagawas** [comment]
still clickable
![image](https://cloud.githubusercontent.com/assets/11714762/21984239/0b810b24-dc1b-11e6-96f9-50d44f4e1260.png)
