### ISSUE TITLE
Validation message for email and phone number needs to be changed

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#66]
The message shown for the email and phone number validation is not readable.

The message can say:
"Suppliers email is invalid on row 2"
"Suppliers contact is invalid on row 2"

![image](https://cloud.githubusercontent.com/assets/11714762/19465853/c4a595ea-9524-11e6-80e5-7dbc152c447c.png)

**Comment by trilokajency** [comment]
done

**Comment by Divyagawas** [comment]
Tested.Thanx
