### ISSUE TITLE
The filters and pagination count should be in the same row

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#705]
Currently can see a separate row for pagination count as shown in the screenshot
![file](https://cloud.githubusercontent.com/assets/11714762/22976235/f2c18f62-f3af-11e6-81ce-b78b0eceaa4d.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Cannot see the changes, please check
![image](https://cloud.githubusercontent.com/assets/11714762/23691224/2f8d7972-03ed-11e7-83f6-f5f78fcacdc5.png)
