### ISSUE TITLE
ASN listing - Created and updated date needs to be readable

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#707]
Created date and updated date - The format is not that readable, Can we make this format same as on the PPt https://docs.google.com/presentation/d/1Vw_sSiz4wkmk-MdMYgqNFJ9o2E5JiiuLlxypxEJ3FXY/edit#slide=id.p9

**Comment by trilokajency** [comment]
have kept it consistent for PO and ASN

**Comment by Divyagawas** [comment]
ok, looks good
