### ISSUE TITLE
Set quantities - Increase spacing between "Unit to ship" and "messages" column

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#729]
![image](https://cloud.githubusercontent.com/assets/11714762/23599441/20c4b07c-0267-11e7-8aa8-4e57378899c2.png)

**Comment by nevesseq** [comment]
@Divyagawas cannot as unit to ship is aligned to right bcoz its a no. and message alignment starts from left

**Comment by Divyagawas** [comment]
We can do it as discussed in the meeting on friday
