### ISSUE TITLE
On editing warehouse, the flash message should say "Warehouse details has been saved successfully"

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#73]
Warehouse
currently : Warehouse information has been saved successfully
expected : Warehouse details saved successfully

![image](https://cloud.githubusercontent.com/assets/11714762/19505911/6673611c-95e4-11e6-8dc3-e38376523b85.png)

Billing details:
currently : Billing information has been saved successfully
expected : Billing details saved successfully

![image](https://cloud.githubusercontent.com/assets/11714762/19505960/c12412fa-95e4-11e6-8323-1ec334a9207f.png)

**Comment by trilokajency** [comment]
done

**Comment by Divyagawas** [comment]
Tested. Thanx
