### ISSUE TITLE
Set quantities | Add products pop up | The sku text looks very small as compared to the product name text size

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#731]
Refer : https://docs.google.com/presentation/d/1Vw_sSiz4wkmk-MdMYgqNFJ9o2E5JiiuLlxypxEJ3FXY/edit#slide=id.p12
![image](https://cloud.githubusercontent.com/assets/11714762/23599588/113bd8fa-0268-11e7-83cc-b0ada6b1fa45.png)

**Comment by nevesseq** [comment]
fixed
