### ISSUE TITLE
Purchase basket | Clone | When the supplier is selected, the cost per quantity has to be populated

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#74]
Currently:
1. Click on "clone" for a product
2. all the details gets cloned.
3. Now select a supplier name from the drop down - "Supplier sku code" gets updated but the  "cost per quantity" remains as was cloned.

Expected:
When the "supplier name" is selected for that particular product - along with supplier sku code, "cost per quantity" should also get populated for that supplier

![image](https://cloud.githubusercontent.com/assets/11714762/19516125/2b53e15e-9618-11e6-9dc6-72c8a76be238.png)

**Comment by trilokajency** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested.Thanx
