### ISSUE TITLE
Purchase basket | Products edit - UI breaks

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#76]
![image](https://cloud.githubusercontent.com/assets/11714762/19516573/3da0a1c4-961a-11e6-913a-a92510ea7899.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
@trilokajency needs to remove the "INR" from"cost per quantity" on edit mode

**Comment by Divyagawas** [comment]
Fixed
