### ISSUE TITLE
Box dimensions in 'mm' to change to 'in.'

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#771]
Refer : https://docs.google.com/presentation/d/1Vw_sSiz4wkmk-MdMYgqNFJ9o2E5JiiuLlxypxEJ3FXY/edit#slide=id.p15
![padding reqd](https://cloud.githubusercontent.com/assets/11714762/23696749/0ecc9e02-040b-11e7-98de-c287d9d837cf.png)

**Comment by nevesseq** [comment]
fixed
