### ISSUE TITLE
Add SKU's to purchase basaket pop up needs to be styled - When products entered from inventory

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#79]
![image](https://cloud.githubusercontent.com/assets/11714762/19547348/fdbdc5aa-96b4-11e6-9ad8-faacffe4564f.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Needs proper styling

![image](https://cloud.githubusercontent.com/assets/11714762/19558524/a397f828-96e8-11e6-99c8-fee69b388045.png)

**Comment by Divyagawas** [comment]
Fixed, Tested.
