### ISSUE TITLE
Discrepancy - The numbers needs to be styled as the others (Bold and big font)

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#796]
Discrepancy column is touching summary section - keep some padding
![padding reqd](https://cloud.githubusercontent.com/assets/11714762/23704913/2bed62a6-042d-11e7-9150-ff64031ec898.png)

**Comment by nevesseq** [comment]
fixed

**Comment by Divyagawas** [comment]
Needs the red and green color
