### ISSUE TITLE
Sentence case - messages

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#811]
1. On creating ASN 
![image](https://cloud.githubusercontent.com/assets/11714762/23786268/024e188a-0592-11e7-828c-b58b94f34ac9.png)

2. Adding products - single /multiple
![image](https://cloud.githubusercontent.com/assets/11714762/23786310/41463806-0592-11e7-87d1-c7979e1f02b6.png)

3. Deleting sku's
![image](https://cloud.githubusercontent.com/assets/11714762/23786326/665366f0-0592-11e7-8032-5f42acf8f146.png)

4. updaing units to ship
![image](https://cloud.githubusercontent.com/assets/11714762/23786335/748a02ec-0592-11e7-9434-50e72cbd243e.png)

5. On copy to all
![image](https://cloud.githubusercontent.com/assets/11714762/23786347/85c18774-0592-11e7-8d51-95313099c230.png)

6. adding/updating/deleting labels
![image](https://cloud.githubusercontent.com/assets/11714762/23786363/931c8ce8-0592-11e7-9839-b59d04614ddc.png)

**Comment by nevesseq** [comment]
fixed
