### ISSUE TITLE
Supplier | catalogs | "select all" check box is needed

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#83]
http://www.btapp.ajency.in/suppliers/view/110

![20](https://cloud.githubusercontent.com/assets/11714762/19548778/22c187a2-96be-11e6-9ff6-6e00158936e8.png)

**Comment by nevesseq** [comment]
checkbox added, @trilokajency  have to add the functionality

**Comment by Divyagawas** [comment]
@trilokajency please look into this
