### ISSUE TITLE
Catalog | Add products pop up | On the add products pop up the "+3 more products" on click does not add 3 more rows

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#9]
For" add supplier" under the tab "catalog" , the add products pop up which comes on clicking the "add product" button on the RHS has a option "+3 more products" which on click does not add 3 more rows

![hidden](https://cloud.githubusercontent.com/assets/11714762/19233192/a02deff6-8f01-11e6-8728-d0ea3a43a528.png)

**Comment by trilokajency** [comment]
Fixed
