### ISSUE TITLE
after copy to all -if 2 products added seperatly - "Add filled to ASN" button shows dissabled

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#905]
![image](https://cloud.githubusercontent.com/assets/11714762/24644387/e52860f0-1930-11e7-905f-1236922fa5d4.png)

**Comment by Divyagawas** [comment]
when quantity fr a new product is added after copy to all - all the copied values gets reset

Needs api changes

**Comment by mohsinAjency** [comment]
fixed

**Comment by ashika123** [comment]
Tested
