### ISSUE TITLE
Add sku's to purchase basket pop | Spelling mistake in the error message

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#96]
![image](https://cloud.githubusercontent.com/assets/11714762/19558545/c48c2ff4-96e8-11e6-8e72-053574a87610.png)

**Comment by trilokajency** [comment]
fixed the functionality as discussed yesterday.
design needs to be fixed

**Comment by Divyagawas** [comment]
@nevesseq please look into this @priority

**Comment by nevesseq** [comment]
typo fixed

**Comment by Divyagawas** [comment]
The message should read "The following sku's cannot be added to the basket as there is no supplier found selling these products"

![image](https://cloud.githubusercontent.com/assets/11714762/19598997/ad060a0c-97bb-11e6-913f-92755dc7dde4.png)

**Comment by Divyagawas** [comment]
Tested.
