### ISSUE TITLE
When there is nothing added in the "purchase basket" for that seller the table should be shown

### ISSUE THREAD

**Issue by Divyagawas** [ajency/PO#97]
Click on some different seller, the supplier and all the other tables for that seller will be empty but should show the table with no data in it instead of showing just the following message

![image](https://cloud.githubusercontent.com/assets/11714762/19589819/2680dfea-978c-11e6-8cb8-3acbc6dfbed5.png)

**Comment by trilokajency** [comment]
fixed

**Comment by Divyagawas** [comment]
Tested.
